swagger: "2.0"
info:
  title: Swirl
  description: swirl sample
  version: 1.0.0
host: api.example.com
basePath: /v1
schemes:
  - https
paths:
  /gk-ccb/account/:
    get:
      summary: get account data
      parameters:
        - in: path
          name: acctId
          required: true
          type: integer
          minimum: 1
      produces:
        - application/json
      responses:
        200:
          description: OK
